[project]
name = "os-schools-test-real-data"
version = "0.1.0"
description = "This repo contains code to test the end-to-end process with real data."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
]
